import type { Payload } from 'payload'
import { evaluateGeofence, isClockInLate } from './AttendanceService'

export type ProcessClockInParams = {
  shiftId: string
  lat: number
  lng: number
  eventType: 'clock_in' | 'clock_out' | 'break_start' | 'break_end' | 'correction'
  qrToken: string
  workerId: string
  tenantId: string
}

/**
 * TimeLogApplicationService
 * 
 * Orchestrates the time tracking process by fetching necessary entities,
 * applying pure domain logic (AttendanceService), and persisting the results.
 */
export async function processClockIn(payload: Payload, params: ProcessClockInParams) {
  const { shiftId, lat, lng, eventType, qrToken, workerId, tenantId } = params

  // 1. Fetch shift + associated department
  const shiftRes = await payload.findByID({
    collection: 'shifts',
    id: shiftId,
    depth: 1,
  })

  if (!shiftRes) {
    throw new Error('Shift not found')
  }

  const department = (shiftRes as any).department as any
  
  // 2. QR Code Validation (Proof of Presence)
  if (!department?.currentDailyToken || department.currentDailyToken !== qrToken) {
    throw new Error('Invalid or expired QR Token. Please scan the current token generated by the Admin.')
  }

  const now = new Date()

  // 3. Delegate math to AttendanceService (pure functions)
  const geofenceStatus = evaluateGeofence(lat, lng, department)
  const isLate =
    eventType === 'clock_in'
      ? isClockInLate(now.getTime(), new Date(shiftRes.startTime).getTime())
      : false

  // 4. Persist time log
  const newLog = await payload.create({
    collection: 'timeLogs',
    data: {
      staffId: workerId,
      tenantId,
      shiftId,
      eventType,
      timestamp: now.toISOString(),
      geolocation: { lat, lng },
      geofenceStatus,
      isLate,
    },
  })

  return {
    geofenceStatus,
    isLate,
    logId: newLog.id
  }
}
