/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    departments: Department;
    certifications: Certification;
    shifts: Shift;
    'job-roles': JobRole;
    timeLogs: TimeLog;
    schedulingRuns: SchedulingRun;
    unavailabilities: Unavailability;
    notifications: Notification;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    shifts: ShiftsSelect<false> | ShiftsSelect<true>;
    'job-roles': JobRolesSelect<false> | JobRolesSelect<true>;
    timeLogs: TimeLogsSelect<false> | TimeLogsSelect<true>;
    schedulingRuns: SchedulingRunsSelect<false> | SchedulingRunsSelect<true>;
    unavailabilities: UnavailabilitiesSelect<false> | UnavailabilitiesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  /**
   * The specific job title/role for scheduling (e.g., Security Guard)
   */
  jobRole?: (string | null) | JobRole;
  role: 'superadmin' | 'admin' | 'supervisor' | 'worker';
  tenantId: string | Tenant;
  /**
   * Maximum hours this person can be scheduled per week.
   */
  maxWeeklyHours?: number | null;
  /**
   * Qualifications/licences held by this staff member.
   */
  certifications?: (string | Certification)[] | null;
  preferences?: {
    /**
     * Departments this staff member prefers to be scheduled in.
     */
    preferredDepartments?: (string | Department)[] | null;
    /**
     * ⚠️ DEPRECATED: Ignored by the scheduling solver. Use the Unavailabilities collection instead.
     */
    unavailableDates?:
      | {
          startDate: string;
          endDate: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-roles".
 */
export interface JobRole {
  id: string;
  /**
   * Name of the role (e.g., Security Guard, Janitor, Supervisor)
   */
  name: string;
  /**
   * Default start time in HH:mm format (e.g., 06:00)
   */
  defaultStartTime?: string | null;
  /**
   * Default end time in HH:mm format (e.g., 14:00)
   */
  defaultEndTime?: string | null;
  /**
   * Hex color code for UI display (e.g., #28CB8B)
   */
  colorCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  slug: string;
  plan: 'basic' | 'compliance' | 'enterprise';
  TenantSettings?:
    | {
        enableOvertimeTracking?: boolean | null;
        requireGeoFencedLogins?: boolean | null;
        activateUnionRestRules?: boolean | null;
        enableShiftBidding?: boolean | null;
        enableSMSNotifications?: boolean | null;
        enableAuditReports?: boolean | null;
        maxWeeklyHours?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'FeatureToggles';
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: string;
  name: string;
  description?: string | null;
  validityPeriodDays?: number | null;
  tenantId: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * A department, zone, floor, or work area within a tenant organisation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: string;
  /**
   * e.g. "ICU Ward A", "Warehouse Bay 3", "Front-of-House"
   */
  name: string;
  /**
   * Physical location descriptor (floor, building, zone, etc.)
   */
  location?: string | null;
  tenantId: string | Tenant;
  /**
   * Certifications every staff member must hold to work in this department.
   */
  requiredBaseCertifications?: (string | Certification)[] | null;
  /**
   * Optional geo-fence for QR clock-in validation.
   */
  geolocation?: {
    latitude?: number | null;
    longitude?: number | null;
    /**
     * Radius in metres where a clock-in is considered on-site.
     */
    radiusMeters?: number | null;
  };
  /**
   * Rotating QR token for proof-of-presence clock-in. Regenerate via POST /:id/generate-qr.
   */
  currentDailyToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shifts".
 */
export interface Shift {
  id: string;
  /**
   * The department or work area this shift is for.
   */
  department: string | Department;
  tenantId: string | Tenant;
  startTime: string;
  endTime: string;
  status: 'draft' | 'published' | 'urgent' | 'filled' | 'closed';
  assignedStaff?: (string | User)[] | null;
  staffingRequirements?:
    | (
        | {
            role: string | JobRole;
            count: number;
            mustHaveCerts?: (string | Certification)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'RoleRequirement';
          }
        | {
            cert: string | Certification;
            count: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'SpecialistReq';
          }
        | {
            minimumSeniorityYears: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'SupervisorRequirement';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeLogs".
 */
export interface TimeLog {
  id: string;
  staffId: string | User;
  tenantId: string | Tenant;
  shiftId?: (string | null) | Shift;
  eventType: 'clock_in' | 'clock_out' | 'break_start' | 'break_end' | 'correction';
  timestamp: string;
  ipAddress?: string | null;
  geolocation?: {
    lat?: number | null;
    lng?: number | null;
  };
  geofenceStatus?: ('within_bounds' | 'outside_bounds' | 'not_checked') | null;
  correctionNote?: string | null;
  /**
   * Automatically flagged if Clock In timestamp > Shift Start Time.
   */
  isLate?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedulingRuns".
 */
export interface SchedulingRun {
  id: string;
  jobId: string;
  tenantId: string | Tenant;
  status: 'pending' | 'completed' | 'failed';
  errorReason?: string | null;
  /**
   * The shifts that were attempted to be filled during this run.
   */
  shiftsInvolved?: (string | Shift)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unavailabilities".
 */
export interface Unavailability {
  id: string;
  workerId: string | User;
  tenantId: string | Tenant;
  startTime: string;
  endTime: string;
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  message: string;
  type: 'info' | 'urgent' | 'shift_alert';
  recipientId: string | User;
  tenantId: string | Tenant;
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'departments';
        value: string | Department;
      } | null)
    | ({
        relationTo: 'certifications';
        value: string | Certification;
      } | null)
    | ({
        relationTo: 'shifts';
        value: string | Shift;
      } | null)
    | ({
        relationTo: 'job-roles';
        value: string | JobRole;
      } | null)
    | ({
        relationTo: 'timeLogs';
        value: string | TimeLog;
      } | null)
    | ({
        relationTo: 'schedulingRuns';
        value: string | SchedulingRun;
      } | null)
    | ({
        relationTo: 'unavailabilities';
        value: string | Unavailability;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  jobRole?: T;
  role?: T;
  tenantId?: T;
  maxWeeklyHours?: T;
  certifications?: T;
  preferences?:
    | T
    | {
        preferredDepartments?: T;
        unavailableDates?:
          | T
          | {
              startDate?: T;
              endDate?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  plan?: T;
  TenantSettings?:
    | T
    | {
        FeatureToggles?:
          | T
          | {
              enableOvertimeTracking?: T;
              requireGeoFencedLogins?: T;
              activateUnionRestRules?: T;
              enableShiftBidding?: T;
              enableSMSNotifications?: T;
              enableAuditReports?: T;
              maxWeeklyHours?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  tenantId?: T;
  requiredBaseCertifications?: T;
  geolocation?:
    | T
    | {
        latitude?: T;
        longitude?: T;
        radiusMeters?: T;
      };
  currentDailyToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  validityPeriodDays?: T;
  tenantId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shifts_select".
 */
export interface ShiftsSelect<T extends boolean = true> {
  department?: T;
  tenantId?: T;
  startTime?: T;
  endTime?: T;
  status?: T;
  assignedStaff?: T;
  staffingRequirements?:
    | T
    | {
        RoleRequirement?:
          | T
          | {
              role?: T;
              count?: T;
              mustHaveCerts?: T;
              id?: T;
              blockName?: T;
            };
        SpecialistReq?:
          | T
          | {
              cert?: T;
              count?: T;
              id?: T;
              blockName?: T;
            };
        SupervisorRequirement?:
          | T
          | {
              minimumSeniorityYears?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-roles_select".
 */
export interface JobRolesSelect<T extends boolean = true> {
  name?: T;
  defaultStartTime?: T;
  defaultEndTime?: T;
  colorCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeLogs_select".
 */
export interface TimeLogsSelect<T extends boolean = true> {
  staffId?: T;
  tenantId?: T;
  shiftId?: T;
  eventType?: T;
  timestamp?: T;
  ipAddress?: T;
  geolocation?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  geofenceStatus?: T;
  correctionNote?: T;
  isLate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedulingRuns_select".
 */
export interface SchedulingRunsSelect<T extends boolean = true> {
  jobId?: T;
  tenantId?: T;
  status?: T;
  errorReason?: T;
  shiftsInvolved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unavailabilities_select".
 */
export interface UnavailabilitiesSelect<T extends boolean = true> {
  workerId?: T;
  tenantId?: T;
  startTime?: T;
  endTime?: T;
  reason?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  message?: T;
  type?: T;
  recipientId?: T;
  tenantId?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}